// apps/mobile/src/App.tsx
import {
  MESH_RECOMMENDED_MAX,
  exceedsMeshRecommendation,
  type WebRtcSignal,
} from "@peerkit-video-chat/core";
import type { MediaController, MediaStreamLike } from "@peerkit-video-chat/media";
import type { JSX } from "react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { StatusBar, StyleSheet, useColorScheme, View } from "react-native";
import { SafeAreaProvider, SafeAreaView } from "react-native-safe-area-context";
import { SettingsSheet } from "./components/SettingsSheet";
import { ToastStack } from "./components/ToastStack";
import { Topbar } from "./components/Topbar";
import { useChatNode } from "./hooks/useChatNode";
import { createMobileMediaController } from "./media";
import { CallScreen } from "./screens/CallScreen";
import { IdentityScreen } from "./screens/IdentityScreen";
import { LobbyScreen } from "./screens/LobbyScreen";
import { PreJoinScreen } from "./screens/PreJoinScreen";
import { loadSettings, setStoredValue } from "./storage";
import { paletteFor, ThemeProvider } from "./theme";
import type {
  DeviceKind,
  RoomMember,
  SavedRoom,
  Screen,
  StreamMap,
  ThemePref,
  Toast,
} from "./types";

const DEFAULT_DEVICES: Record<DeviceKind, string> = {
  camera: "",
  microphone: "",
  speaker: "",
};

function toastMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

function normalizedRoomName(roomName: string): string {
  return roomName.trim().replace(/\s+/g, "-").toLowerCase();
}

export default function App(): JSX.Element {
  const systemScheme = useColorScheme();
  const chat = useChatNode();
  const [screen, setScreen] = useState<Screen>("initializing");
  const [selfName, setSelfName] = useState("");
  const [selfMic, setSelfMic] = useState(true);
  const [selfCam, setSelfCam] = useState(true);
  const [currentRoom, setCurrentRoom] = useState<string | null>(null);
  const [joinTime, setJoinTime] = useState(0);
  const [savedRooms, setSavedRooms] = useState<SavedRoom[]>([]);
  const [theme, setTheme] = useState<ThemePref>("system");
  const [devices, setDevices] = useState<Record<DeviceKind, string>>(DEFAULT_DEVICES);
  const [toasts, setToasts] = useState<Toast[]>([]);
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [localStream, setLocalStream] = useState<MediaStreamLike | null>(null);
  const [remoteStreams, setRemoteStreams] = useState<StreamMap>(new Map());
  const [speakingPeers, setSpeakingPeers] = useState<ReadonlySet<string>>(new Set());
  const knownPeers = useRef(new Set<string>());
  const mediaRef = useRef<MediaController | null>(null);

  const media = useMemo(() => {
    const controller = createMobileMediaController(async (toAgent, signal) => {
      await chat.sendSignal(toAgent, signal);
    });
    mediaRef.current = controller;
    return controller;
  }, [chat.sendSignal]);

  const roomMembers: RoomMember[] =
    chat.state.room.kind === "inRoom" ? chat.state.room.members : [];
  const activeMembers = chat.state.networkRooms.find((room) => room.name === currentRoom)?.members ?? [];
  const themeResolved = theme === "system" ? (systemScheme === "light" ? "light" : "dark") : theme;
  const palette = paletteFor(themeResolved);

  const pushToast = useCallback((message: string, kind: Toast["kind"] = "error") => {
    const id = `${Date.now()}-${Math.random()}`;
    setToasts((prev) => [...prev, { id, message, kind }]);
    setTimeout(() => {
      setToasts((prev) => prev.filter((toast) => toast.id !== id));
    }, 5000);
  }, []);

  useEffect(() => {
    loadSettings()
      .then((settings) => {
        setSavedRooms(settings.savedRooms);
        setTheme(settings.theme);
        setDevices(settings.devices);
        media.setPreferredDevices(settings.devices.camera, settings.devices.microphone);
        if (settings.username) {
          void handleSetUsername(settings.username);
        } else {
          setScreen("identity");
        }
      })
      .catch(() => {
        setScreen("identity");
      });
  }, [media]);

  useEffect(() => {
    media.setStreamCallback((agentId, stream) => {
      setRemoteStreams((prev) => {
        const next = new Map(prev);
        if (stream === null) {
          next.delete(agentId);
        } else {
          next.set(agentId, stream);
        }
        return next;
      });
    });
    media.setSpeakingCallback((agentId, speaking) => {
      setSpeakingPeers((prev) => {
        const next = new Set(prev);
        if (speaking) {
          next.add(agentId);
        } else {
          next.delete(agentId);
        }
        return next;
      });
    });
  }, [media]);

  // Tear down the media controller and chat node when the app unmounts so peer
  // connections and the libp2p node don't outlive the React tree.
  useEffect(() => {
    return () => {
      media.closeAll();
      void chat.shutDown();
    };
    // `media` and `chat.shutDown` are stable for the app's lifetime.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    if (screen !== "call") {
      knownPeers.current.clear();
      return;
    }
    const currentIds = new Set(roomMembers.map((member) => member.agentId));
    for (const agentId of Array.from(knownPeers.current)) {
      if (!currentIds.has(agentId)) knownPeers.current.delete(agentId);
    }
    for (const member of roomMembers) {
      if (member.agentId === chat.state.agentId || knownPeers.current.has(member.agentId)) continue;
      knownPeers.current.add(member.agentId);
      if (chat.state.agentId < member.agentId) {
        media.initiateCall(member.agentId).catch((error: unknown) => {
          pushToast(toastMessage(error));
        });
      }
    }
  }, [chat.state.agentId, media, pushToast, roomMembers, screen]);

  // Warn once when a room reaches the comfortable mesh ceiling; re-arm when it
  // drops back below, so growing past the limit warns again but a steady large
  // room doesn't nag on every roster update (mirrors the desktop latch).
  const meshWarned = useRef(false);
  useEffect(() => {
    if (exceedsMeshRecommendation(roomMembers.length)) {
      if (!meshWarned.current) {
        meshWarned.current = true;
        pushToast(
          `${roomMembers.length} people in this room. Calls are smoothest with ${MESH_RECOMMENDED_MAX} or fewer — audio and video quality may drop beyond that.`,
          "warn",
        );
      }
    } else {
      meshWarned.current = false;
    }
  }, [pushToast, roomMembers.length]);

  async function handleSetUsername(name: string): Promise<void> {
    setSelfName(name);
    await setStoredValue("username", name);
    try {
      await chat.start(name, (fromAgent: string, signal: WebRtcSignal) => {
        mediaRef.current?.handleSignal(fromAgent, signal).catch((error: unknown) => {
          console.warn("handleSignal error:", error);
        });
      });
      setScreen("lobby");
    } catch (error) {
      pushToast(toastMessage(error));
      setScreen("identity");
    }
  }

  function handleJoinIntent(roomName: string): void {
    const normalized = normalizedRoomName(roomName);
    if (!normalized.replace(/-/g, "")) return;
    const existing = savedRooms.find((room) => room.name === normalized);
    const nextSaved = existing
      ? [{ ...existing, lastUsed: Date.now() }, ...savedRooms.filter((room) => room.name !== normalized)]
      : [{ name: normalized, lastUsed: Date.now() }, ...savedRooms];
    setSavedRooms(nextSaved);
    void setStoredValue("savedRooms", nextSaved);
    setCurrentRoom(normalized);
    setScreen("prejoin");
  }

  async function handleConfirmJoin(): Promise<void> {
    if (currentRoom === null) return;
    media.setMuted(!selfMic);
    await media.setCamMuted(!selfCam);
    await chat.joinRoom(currentRoom);
    setJoinTime(Date.now());
    setScreen("call");
  }

  async function handleLeave(): Promise<void> {
    await chat.leaveRoom();
    media.closeAll();
    setLocalStream(null);
    setRemoteStreams(new Map());
    setCurrentRoom(null);
    setScreen("lobby");
  }

  function handleToggleMic(): void {
    media.setMuted(selfMic);
    setSelfMic((prev) => !prev);
  }

  async function handleToggleCam(): Promise<void> {
    await media.setCamMuted(selfCam);
    setSelfCam((prev) => !prev);
    setLocalStream(media.getLocalStream());
  }

  function handleSetTheme(nextTheme: ThemePref): void {
    setTheme(nextTheme);
    void setStoredValue("theme", nextTheme);
  }

  function handleRemoveSaved(roomName: string): void {
    const nextSaved = savedRooms.filter((room) => room.name !== roomName);
    setSavedRooms(nextSaved);
    void setStoredValue("savedRooms", nextSaved);
  }

  const appContent = (() => {
    if (screen === "identity") {
      return <IdentityScreen onContinue={(name) => void handleSetUsername(name)} />;
    }
    if (screen === "initializing") {
      return <View style={styles.fill} />;
    }
    if (screen === "lobby") {
      return (
        <LobbyScreen
          selfName={selfName}
          savedRooms={savedRooms}
          activeRooms={chat.state.networkRooms}
          onJoin={handleJoinIntent}
          onRemoveSaved={handleRemoveSaved}
        />
      );
    }
    if (screen === "prejoin" && currentRoom !== null) {
      return (
        <PreJoinScreen
          selfAgentId={chat.state.agentId}
          selfName={selfName}
          roomName={currentRoom}
          selfMic={selfMic}
          selfCam={selfCam}
          activeMembers={activeMembers}
          media={media}
          onToggleMic={handleToggleMic}
          onToggleCam={() => void handleToggleCam()}
          onJoin={() => {
            handleConfirmJoin().catch((error: unknown) => pushToast(toastMessage(error)));
          }}
          onBack={() => {
            setCurrentRoom(null);
            setScreen("lobby");
          }}
          onError={(error) => pushToast(toastMessage(error))}
        />
      );
    }
    if (screen === "call" && currentRoom !== null) {
      return (
        <CallScreen
          selfAgentId={chat.state.agentId}
          selfName={selfName}
          selfMic={selfMic}
          selfCam={selfCam}
          roomName={currentRoom}
          members={roomMembers}
          joinTime={joinTime}
          messages={chat.state.chatMessages}
          localStream={localStream ?? media.getLocalStream()}
          remoteStreams={remoteStreams}
          speakingPeers={speakingPeers}
          onToggleMic={handleToggleMic}
          onToggleCam={() => void handleToggleCam()}
          onLeave={() => {
            handleLeave().catch((error: unknown) => pushToast(toastMessage(error), "warn"));
          }}
          onSendChat={(body) => {
            chat.sendChat(body).catch((error: unknown) => pushToast(toastMessage(error), "warn"));
          }}
        />
      );
    }
    return <View style={styles.fill} />;
  })();

  return (
    <SafeAreaProvider>
      <ThemeProvider palette={palette}>
        <SafeAreaView style={[styles.shell, { backgroundColor: palette.bg }]}>
          <StatusBar barStyle={palette.barStyle} />
          {screen !== "identity" && screen !== "initializing" ? (
            <Topbar
              selfName={selfName}
              relayConnected={chat.state.relayConnected}
              peerStats={chat.state.peerStats}
              onOpenSettings={() => setSettingsOpen(true)}
            />
          ) : null}
          <View style={styles.fill}>{appContent}</View>
          <SettingsSheet
            visible={settingsOpen}
            theme={theme}
            devices={devices}
            onTheme={handleSetTheme}
            onClose={() => setSettingsOpen(false)}
          />
          <ToastStack
            toasts={toasts}
            onDismiss={(id) => setToasts((prev) => prev.filter((toast) => toast.id !== id))}
          />
        </SafeAreaView>
      </ThemeProvider>
    </SafeAreaProvider>
  );
}

const styles = StyleSheet.create({
  shell: {
    flex: 1,
  },
  fill: {
    flex: 1,
  },
});

// apps/desktop/src/renderer/src/App.svelte
<script lang="ts">
  import Topbar from './components/Topbar.svelte';
  import ToastStack from './components/ToastStack.svelte';
  import type { Toast } from './components/ToastStack.svelte';
  import IdentityScreen from './screens/IdentityScreen.svelte';
  import LobbyScreen from './screens/LobbyScreen.svelte';
  import PreJoinScreen from './screens/PreJoinScreen.svelte';
  import CallScreen from './screens/CallScreen.svelte';
  import {
    setStreamCallback,
    setSpeakingCallback,
    setMuted,
    setCamMuted,
    setPreferredDevices,
    handleSignal,
    initiateCall,
    closeAll,
    setPeerNameResolver,
    getLocalStream,
  } from './media.js';
  import { remoteStreams, speakingPeers, remoteVideoLive } from './lib/stores.js';
  import type { PeerStats } from '@peerkit-video-chat/core';
  import {
    MESH_RECOMMENDED_MAX,
    exceedsMeshRecommendation,
  } from '@peerkit-video-chat/core/mesh';

  declare const __APP_VERSION__: string;

  type Screen = 'identity' | 'initializing' | 'lobby' | 'prejoin' | 'call';
  type ThemePref = 'system' | 'light' | 'dark';
  type ThemeResolved = 'dark' | 'light';

  interface SavedRoom {
    name: string;
    lastUsed: number;
  }

  interface RoomMember {
    agentId: string;
    displayName: string;
  }

  interface ChatMessage {
    id: string;
    agentId: string;
    displayName: string;
    body: string;
    t: number;
  }

  // ── State ───────────────────────────────────────────────────────

  let screen = $state<Screen>('initializing');
  let selfName = $state('');
  let selfAgentId = $state('');
  let relayAddr = $state('');
  let relayConnected = $state(false);
  let peerStats = $state<PeerStats | null>(null);
  let currentRoom = $state<string | null>(null);
  let joinTime = $state(0);
  let selfMic = $state(true);
  let selfCam = $state(true);
  interface ActiveRoom {
    name: string;
    members: Array<{ agentId: string; displayName: string }>;
  }

  type DeviceKind = 'camera' | 'microphone' | 'speaker';

  let roomMembers = $state<RoomMember[]>([]);
  let chatMessages = $state<ChatMessage[]>([]);
  let savedRooms = $state<SavedRoom[]>([]);
  let activeRooms = $state<ActiveRoom[]>([]);
  let deviceIds = $state<Record<DeviceKind, string>>({ camera: '', microphone: '', speaker: '' });

  // Toasts
  let toasts = $state<Toast[]>([]);

  function pushToast(message: string, kind: Toast['kind'] = 'error') {
    const id = String(Date.now() + Math.random());
    toasts = [...toasts, { id, message, kind }];
    setTimeout(() => { toasts = toasts.filter(t => t.id !== id); }, 5000);
  }

  function dismissToast(id: string) {
    toasts = toasts.filter(t => t.id !== id);
  }

  function toastMessage(err: unknown): string {
    if (err instanceof Error) return err.message;
    if (typeof err === 'string') return err;
    return 'An unexpected error occurred';
  }

  // Theme
  let themePref = $state<ThemePref>('system');
  let systemDark = $state(
    window.matchMedia?.('(prefers-color-scheme: dark)').matches ?? true
  );
  const themeResolved = $derived<ThemeResolved>(
    themePref === 'system' ? (systemDark ? 'dark' : 'light') : themePref
  );

  // ── Store load + auto-init ──────────────────────────────────────

  $effect(() => {
    window.app.store.load().then((stored) => {
      savedRooms = (stored['savedRooms'] as SavedRoom[] | undefined) ?? [];
      themePref = (stored['theme'] as ThemePref | undefined) ?? 'system';
      const storedDevices = stored['devices'] as Record<DeviceKind, string> | undefined;
      if (storedDevices) {
        deviceIds = storedDevices;
        setPreferredDevices(storedDevices.camera, storedDevices.microphone);
      }
      const username = stored['username'] as string | undefined;
      if (username) {
        onSetUsername(username).catch(() => { screen = 'identity'; });
      } else {
        screen = 'identity';
      }
    }).catch(() => { screen = 'identity'; });
  });

  // ── Theme setup ─────────────────────────────────────────────────

  $effect(() => {
    const mq = window.matchMedia('(prefers-color-scheme: dark)');
    const update = () => { systemDark = mq.matches; };
    mq.addEventListener?.('change', update);
    return () => mq.removeEventListener?.('change', update);
  });

  // ── WebRTC callbacks ────────────────────────────────────────────

  $effect(() => {
    setStreamCallback((agentId, stream) => {
      if (stream === null) {
        remoteStreams.update(m => {
          const n = new Map(m);
          n.delete(agentId);
          return n;
        });
        remoteVideoLive.update(s => {
          const n = new Set(s);
          n.delete(agentId);
          return n;
        });
      } else {
        remoteStreams.update(m => {
          const n = new Map(m);
          n.set(agentId, stream);
          return n;
        });
      }
    });

    setSpeakingCallback((agentId, speaking) => {
      speakingPeers.update(s => {
        const n = new Set(s);
        if (speaking) n.add(agentId); else n.delete(agentId);
        return n;
      });
    });
  });

  // Let webrtc logs name peers by their roster display name rather than a raw id.
  $effect(() => {
    setPeerNameResolver((id) =>
      roomMembers.find((m) => m.agentId === id)?.displayName,
    );
  });

  // ── WebRTC call initiation ──────────────────────────────────────
  // Peers we have already initiated or accepted a call with this session.
  // Plain Set (not $state) — used only for deduplication, not for rendering.
  let knownPeers = new Set<string>();

  $effect(() => {
    if (screen !== 'call') {
      knownPeers = new Set();
      return;
    }
    for (const m of roomMembers) {
      if (m.agentId === selfAgentId) continue;
      if (!knownPeers.has(m.agentId)) {
        knownPeers.add(m.agentId);
        // Lower agent ID is the offerer — prevents both sides calling simultaneously.
        if (selfAgentId < m.agentId) {
          initiateCall(m.agentId).catch((err: unknown) => {
            pushToast(toastMessage(err));
          });
        }
      }
    }
  });

  // ── IPC event handlers ──────────────────────────────────────────

  $effect(() => {
    const unsubState = window.app.onState((view) => {
      if (view.kind === 'inRoom') {
        roomMembers = view.members.map(m => ({
          agentId: m.agentId,
          displayName: m.displayName,
        }));
      } else {
        roomMembers = [];
      }
    });

    const unsubNetworkRooms = window.app.onNetworkRooms((rooms) => {
      activeRooms = rooms;
    });

    const unsubPeerStats = window.app.onPeerStats((stats) => {
      peerStats = stats;
    });

    const unsubRelayConnected = window.app.onRelayConnected((connected) => {
      relayConnected = connected;
    });

    const unsubChat = window.app.onChat((incoming) => {
      // skip echo of own messages — we add them optimistically in onSendChat
      if (incoming.from === selfAgentId) return;
      chatMessages = [
        ...chatMessages,
        {
          id: 'chat-' + Date.now() + '-' + Math.random(),
          agentId: incoming.from,
          displayName: incoming.displayName,
          body: incoming.body,
          t: incoming.ts,
        },
      ];
    });

    const unsubSignal = window.app.onSignal((fromAgent, signal) => {
      handleSignal(fromAgent, signal).catch((err: unknown) => {
        console.warn('handleSignal error:', err);
      });
    });

    const unsubMediaState = window.app.onMediaState((fromAgent, camera) => {
      remoteVideoLive.update(s => {
        const n = new Set(s);
        if (camera) n.add(fromAgent); else n.delete(fromAgent);
        return n;
      });
    });

    return () => {
      unsubState();
      unsubNetworkRooms();
      unsubPeerStats();
      unsubRelayConnected();
      unsubChat();
      unsubSignal();
      unsubMediaState();
    };
  });

  // Warn once when a room reaches the comfortable mesh ceiling; re-arm when it
  // drops back below, so growing past the limit warns again but a steady large
  // room doesn't nag on every roster update.
  let meshWarned = false;
  $effect(() => {
    if (exceedsMeshRecommendation(roomMembers.length)) {
      if (!meshWarned) {
        meshWarned = true;
        pushToast(
          `${roomMembers.length} people in this room. Calls are smoothest with ` +
            `${MESH_RECOMMENDED_MAX} or fewer — audio and video quality may drop beyond that.`,
          'warn',
        );
      }
    } else {
      meshWarned = false;
    }
  });

  // ── State machine handlers ──────────────────────────────────────

  async function onSetUsername(name: string) {
    selfName = name;
    void window.app.store.set('username', name);
    try {
      const result = await window.app.init(name);
      selfAgentId = result.agentId;
      relayAddr = result.relayAddr;
      relayConnected = result.relayConnected;
      void window.app.getPeerStats().then((s) => { if (s) peerStats = s; });
      if (result.room.kind === 'inRoom') {
        // The chat node was already in a room — the renderer reloaded while a
        // call was live (e.g. closing/opening the laptop lid). Drop straight
        // back into the call instead of stranding us in the lobby, where
        // re-joining would fail with "already in a room".
        currentRoom = result.room.room;
        roomMembers = result.room.members.map(m => ({
          agentId: m.agentId,
          displayName: m.displayName,
        }));
        // The renderer reloaded, so no local media has been re-acquired yet:
        // seed the mic/camera controls from what is actually live (nothing)
        // rather than their defaults, so the buttons don't claim we are sending
        // audio/video, and tell peers our camera is off to match.
        const stream = getLocalStream();
        selfMic = stream?.getAudioTracks().some(t => t.readyState === 'live') ?? false;
        selfCam = stream?.getVideoTracks().some(t => t.readyState === 'live') ?? false;
        void window.app.setCameraState(selfCam);
        joinTime = Date.now();
        screen = 'call';
      } else {
        screen = 'lobby';
      }
    } catch (err) {
      pushToast(toastMessage(err));
      screen = 'identity';
    }
  }

  function onJoinRoom(roomName: string) {
    const normalized = roomName.trim().toLowerCase();
    // Bump or add saved room
    const existing = savedRooms.find(r => r.name === normalized);
    if (existing) {
      savedRooms = [
        { ...existing, lastUsed: Date.now() },
        ...savedRooms.filter(r => r.name !== normalized),
      ];
    } else {
      savedRooms = [{ name: normalized, lastUsed: Date.now() }, ...savedRooms];
    }
    void window.app.store.set('savedRooms', $state.snapshot(savedRooms));
    currentRoom = normalized;
    screen = 'prejoin';
  }

  function onRemoveSaved(name: string) {
    savedRooms = savedRooms.filter(r => r.name !== name);
    void window.app.store.set('savedRooms', $state.snapshot(savedRooms));
  }

  async function onConfirmJoin(audio: boolean, video: boolean) {
    selfMic = audio;
    selfCam = video;
    setMuted(!audio);
    try {
      await setCamMuted(!video);
      // Set before joining so the join announcement carries the right camera
      // state and peers render our tile correctly from the start.
      await window.app.setCameraState(video);
      await window.app.joinRoom(currentRoom!);
      joinTime = Date.now();
      screen = 'call';
    } catch (err) {
      pushToast(toastMessage(err));
    }
  }

  async function onLeave() {
    try {
      await window.app.leaveRoom();
    } catch (err) {
      pushToast(toastMessage(err), 'warn');
    }
    closeAll();
    currentRoom = null;
    chatMessages = [];
    screen = 'lobby';
  }

  function onToggleMic() {
    setMuted(selfMic);
    selfMic = !selfMic;
  }

  async function onToggleCam() {
    try {
      await setCamMuted(selfCam);
      selfCam = !selfCam;
      void window.app.setCameraState(selfCam);
    } catch (err) {
      pushToast(toastMessage(err));
    }
  }

  async function onSendChat(body: string) {
    try {
      await window.app.sendChat(body);
      // Also show in our own chat immediately (optimistic)
      chatMessages = [
        ...chatMessages,
        {
          id: 'self-chat-' + Date.now(),
          agentId: selfAgentId,
          displayName: selfName,
          body,
          t: Date.now(),
        },
      ];
    } catch (err) {
      pushToast(toastMessage(err), 'warn');
    }
  }

  function onSetTheme(pref: ThemePref) {
    themePref = pref;
    void window.app.store.set('theme', pref);
  }

  function onSetDevice(kind: DeviceKind, id: string) {
    deviceIds = { ...deviceIds, [kind]: id };
    void window.app.store.set('devices', $state.snapshot(deviceIds));
    if (kind === 'camera' || kind === 'microphone') {
      setPreferredDevices(deviceIds.camera, deviceIds.microphone);
    }
  }
</script>

<div class="app" data-theme={themeResolved} data-density="spacious">
  {#if screen !== 'identity' && screen !== 'initializing'}
    <Topbar
      {selfName}
      {selfAgentId}
      {relayAddr}
      {relayConnected}
      {peerStats}
      {themePref}
      {onSetTheme}
      {deviceIds}
      {onSetDevice}
    />
  {/if}
  <div class="page">
    {#if screen === 'identity'}
      <IdentityScreen onContinue={onSetUsername} />
    {:else if screen === 'initializing'}
      <!-- blank while auto-connecting with saved username -->
    {:else if screen === 'lobby'}
      <LobbyScreen
        {selfName}
        {savedRooms}
        {activeRooms}
        appVersion={__APP_VERSION__}
        onJoin={onJoinRoom}
        {onRemoveSaved}
      />
    {:else if screen === 'prejoin'}
      <PreJoinScreen
        {selfAgentId}
        {selfName}
        {currentRoom}
        {selfMic}
        {selfCam}
        activeMembers={activeRooms.find(r => r.name === currentRoom)?.members ?? []}
        onToggleAudio={onToggleMic}
        onToggleVideo={onToggleCam}
        onJoin={onConfirmJoin}
        onBack={() => { currentRoom = null; screen = 'lobby'; }}
        onError={(err) => pushToast(toastMessage(err))}
      />
    {:else if screen === 'call'}
      <CallScreen
        {selfAgentId}
        {selfName}
        {selfMic}
        {selfCam}
        {currentRoom}
        {roomMembers}
        {joinTime}
        {chatMessages}
        speakerId={deviceIds.speaker}
        {onToggleMic}
        {onToggleCam}
        {onLeave}
        onSendChat={onSendChat}
      />
    {/if}
  </div>
  <ToastStack {toasts} onDismiss={dismissToast} />
</div>
